### PR TITLE
add and correctly style hoverref

### PR DESCRIPTION
**Pull request by jpfeuffer**
supersedes #85 

## PR checklist

- [ ] I have added description of the change I'm proposing in the OpenMS Documentation.
- [ ] I have read and followed [OpenMS Documentation Contributing guidelines](CONTRIBUTING.md).
- [ ] I have attached a screenshot of the relevant area after this change.
- [ ] `CHANGELOG.md` is updated.
- [ ] I have added my name in [CONTRIBUTING.md](CONTRIBUTING.md#openms-documentation-contributors).

### CODE REVIEW

**Comment by ghost** [comment]
Would you be able to provide screenshots @jpfeuffer?

**Comment by jpfeuffer** [comment]
Of the styling, yes, of the tooltips no (they do not work locally due to cross-domain JS code, trying to load local files)

**Comment by jpfeuffer** [comment]
Bildschirmfoto 2022-08-02 um 16 46 45

**Comment by jpfeuffer** [comment]
Now gray. Should be more consistent

Bildschirmfoto 2022-08-02 um 16 52 31

**Comment by jpfeuffer** [comment]
Or with little question marks
Bildschirmfoto 2022-08-02 um 18 16 30

**Comment by ghost** [comment]
@jpfeuffer can the question marks be bigger?

**Comment by timosachsenberg** [comment]
hmm I like they grey dots a bit better... having so many question marks looks a bit odd (like missing references in a latex document ;) )

**Comment by ghost** [comment]
I don't think the grey dots distinguish them enough. Could the text be a different color like [here](https://github.com/readthedocs/sphinx_rtd_theme/issues/877)?

**Comment by jpfeuffer** [comment]
I think your linked issue is about something else. The different color just is a coincidence. Maybe it means that the link was clicked.
But I am not against a different color, if you think that solves it and does not confuse users. (It will definitely not be purple since I find it looks like clicked links)

**Comment by jpfeuffer** [comment]
> hmm I like they grey dots a bit better... having so many question marks looks a bit odd (like missing references in a latex document ;) )

It can be an info icon instead. Just a suggestion.

**Comment by ghost** [comment]
> I think your linked issue is about something else. The different color just is a coincidence. Maybe it means that the link was clicked. But I am not against a different color, if you think that solves it and does not confuse users. (It will definitely not be purple since I find it looks like clicked links)

I think a different color or an icon would work. Personally, I prefer a different color as an icon could clutter the text.

**Review by tapaswenipathak — DISMISSED** [review]
Re: I like the default setting but it doesn't work: https://discord.com/channels/832282841836159006/969233556788359228/984390409126051871.

locally:
Screenshot 2022-08-03 at 5 19 59 PM
Screenshot 2022-08-03 at 5 20 16 PM

(Please properly test before requesting reviews/tagging.)

**Comment by jpfeuffer** [comment]
@tapaswenipathak Of course, it works! Tested on Chrome and Safari and now built and deployed specifically for you.
https://openms.readthedocs.io/en/hoverref/

(Please double-check your git workflow before reviewing)

**Review by timosachsenberg — APPROVED** [review]

**Pull request merged**
