### PR TITLE
Configured settings to add tooltips to underlined terms in documentation

### PR DESCRIPTION
**Pull request by ghost**
## Describe the change

I've added tooltips to underlined terms by adding a couple of settings to the conf.py file and adding the hoverxref package to requirements.txt:
Screen Shot 2022-06-09 at 4 57 21 pm

Screen Shot 2022-06-09 at 5 02 05 pm

Screen Shot 2022-06-09 at 5 02 47 pm

Check out [this link](https://greengypsy-staging-openms.readthedocs.io/en/add-tooltips-v2/docs/introduction.html#background) to see all the changes built.

## PR checklist

- [ ] I have added description of the change I'm proposing in the OpenMS Documentation.
- [ ] I have read and followed [OpenMS Documentation Contributing guidelines](CONTRIBUTING.md).
- [ ] I have attached a screenshot of the relevant area after this change.
- [ ] `CHANGELOG.md` is updated.
- [ ] I have added my name in [CONTRIBUTING.md](CONTRIBUTING.md#openms-documentation-contributors).

### CODE REVIEW

**Comment by jpfeuffer** [comment]
Question: do we want them underlined or can we add a little superscript question mark?
Currently they look like hyperlinks. I would probably at least change the color.

**Comment by ghost** [comment]
> Question: do we want them underlined or can we add a little superscript question mark? Currently they look like hyperlinks. I would probably at least change the color.

I'm not sure how to extend other css files without completely overriding them. Can we merge this request and make a ticket for the next iteration? I will need to look into it further to come up with a solution.

**Comment by jpfeuffer** [comment]
Ok. Open the ticket, link it and merge.

**Comment by ghost** [comment]
The new issue is [here](https://github.com/OpenMS/OpenMS-docs/issues/86)

**Comment by jpfeuffer** [comment]
What is the status here? Ready to merge?

**Comment by jpfeuffer** [comment]
I was checking recently and tooltips still look *exactly* like links. I don't like it.

**Comment by jpfeuffer** [comment]
Maybe it is on a different branch or so but I am confused with all the forks and branches.

**Comment by ghost** [comment]
Nobody has worked on this issue for a while. If I have time, I will look into it.

**Pull request closed without merging**
