### PR TITLE
Final touches

### LINKED ISSUE #109: Remove references to OMSSA
@tjeerdijk has mentioned that OMSSA is no longer supported, so we will need to remove any references to OMSSA in the documentation.

### LINKED ISSUE #121: Missing links in "How OpenMS Works"
Every paragraph on this page ends with "View the ... here." But the links are missing.

## Description of the documentation bug

- [x] I have attached screenshots of the incorrect documentation

## Expected behaviour
There should be a link at the end of each paragraph, e.g. attached to the last word "here".

image

### LINKED ISSUE #122: Inconsistent error message visualization, Windows install instructions
## Description of the documentation bug

- [x] I have attached screenshots of the incorrect documentation

In Installation guides, Windows, under Known Issues in points 1 and 2 two error messages are shown. They are visualized in different ways.

## Expected behaviour

These error messages should be portrayed in the same way, preferably in their own boxes like the second case already is.

image

### LINKED ISSUE #123: German link in installation instructions for Windows
## Description of the documentation bug

Under Installation Guides, Windows, Known Issues, the 4. case about .NET Framework 3.5 installation links to the German Microsoft help page. 

## Expected behaviour

The link should point to the equivalent English page here: https://docs.microsoft.com/en-us/dotnet/framework/install/dotnet-35-windows

### LINKED ISSUE #124: OpenMS Applications page
Several issues on the OpenMS Applications page, some of them are up for discussion:
- [x] INI files are a common way to configure software. The INIFileEditor description makes it sound like it could potentially be used for INI files in general, but OpenMS uses an unusual format (XML) that is rarely used for INI files. This could be made a bit more clear, e.g. by changing the first sentence to "A GUI application used to edit OpenMS specific INI files" or "TOPP INI files"
- [x] The second sentence in the TOPPView description seems out of place: "Read more in-depth documentation about TOPPView." The third sentence links to the visualization section, so this second sentence looks redundant without a link to another resource.
- [x] The SwathWizard section ends abruptly, without a ".". There is also a "page" missing at the end, I think.
- [x] I don't believe the "typical workflow" at the bottom is typical. In my experience TOPP tools are rarely executed from the TOPPView interface, especially using INI files, since the INIFileEditor is essentially build in into TOPPView as well. But it is certainly a "possible workflow". Also there is a first step missing: generating a tool specific INI file with default parameters, before changing the parameters. Another example of a workflow would be: generate INI file -> change params with INIFileEditor -> run TOPP tool from command line or a script, using the INI file instead of a dozen command line parameters -> use TOPPView to visualize input data and the output of the TOPP tool
- [x] Is it a good idea to call this page "OpenMS Applications"? We have a different idea about what that means on the OpenMS website. An "Application" also doesn't require a GUI. This should be called "OpenMS GUIs" or "OpenMS Graphical User Interfaces" or something similar.

### LINKED ISSUE #125: Content about File Formats
E.g. in the "Introduction to TOPP" and "Command Line Interface" it is stated that TOPP tools only accept mzML files as input. That is actually only true for some TOPP tools, maybe even a minority.

1. TOPP tools are supposed to be chained together, so obviously the output of one tool can be the input for the next. So many tools accept featureXML, idMXL and other file formats for the "-in" input parameter.
2. The "-out" description in "Command Line Interface" also mentions the output file format has to be mzML. Tools that take an mzML and return another mzML are definitely in a minority. Most return featureXML, consensusXML or idXML files.
3. mzML is a standardized format defined independently of OpenMS and used by many. featureXML, consensusXML and idXML are OpenMS internal formats and rarely used by other tools. Therefore we support several additional standardized formats for data repositories and interoperability with other pipelines, e.g. MzIdentML for ID data, mzTAB for ID and Quantification data and a few more.
4. Even for spectra data, many tools support additional formats, like mzXML or MGF. mzML is just the one most consistently supported and the one we strongly recommend to use in most cases.

It is not necessary to list all possible formats or anything, but the text should reflect that the tools can have different input and output formats, sometimes multiple options for both, and that we support open formats for interoperability (mzML, mzIdentML, mzTAB are such formats, featureXML, consensusXML and idXML are actually not and only used within TOPP internally)

E.g. the FileFilter used as an example in CLI supports mzML, featureXML and consensusXML as input and output, and has separate subsets of parameters to define filters for each of those.

### PR DESCRIPTION
**Pull request by ghost**
## Describe the change

This PR aims to close the following issues:
- Closes #125. 
- Closes #124.
- Closes #123.
- Closes #122.
- Closes #121.
- Closes #109. 

View the final output [here](https://greengypsy-staging-openms.readthedocs.io/en/final-touches/docs/#).
## PR checklist

- [x] I have added description of the change I'm proposing in the OpenMS Documentation.
- [x] I have read and followed [OpenMS Documentation Contributing guidelines](CONTRIBUTING.md).
- [ ] I have attached a screenshot of the relevant area after this change.
- [ ] `CHANGELOG.md` is updated.
- [ ] I have added my name in [CONTRIBUTING.md](CONTRIBUTING.md#openms-documentation-contributors).

### CODE REVIEW

**Comment by timosachsenberg** [comment]
Hi. There are quite a bunch of deleted files. I did not look into detail but this is intended right?

**Comment by ghost** [comment]
> Hi. There are quite a bunch of deleted files. I did not look into detail but this is intended right?

Yes, I only deleted redundant and blank files.

**Comment by timosachsenberg** [comment]
- https://greengypsy-staging-openms.readthedocs.io/en/final-touches/docs/introduction/about-open-ms.html is slightly redundant
- https://greengypsy-staging-openms.readthedocs.io/en/final-touches/docs/introduction/background.html needs a bit of rework I think. See e.g., the section in https://pyopenms.readthedocs.io/en/latest/introduction.html#background . This seems a bit more complete.
- https://greengypsy-staging-openms.readthedocs.io/en/final-touches/docs/introduction/how-openms-works.html could require some rework. e.g., it is referring to images that are not in it. Also, I think it would be better to group the entry points to distinguish users that want to develop (e.g., computer scientists/bioinformaticians) and those that want to apply OpenMS tools (life scientists / also bioinformaticians)
- the links to the installation instructions at "Use OpenMS graphical applications" seem a bit odd currently. Why are they referenced here?
- make a "Note:" field for "KNIME and Galaxy are recommended over TOPPAS, which can also be used to create workflows however is no longer supported."
- https://greengypsy-staging-openms.readthedocs.io/en/final-touches/docs/run-workflows-with-openms-tools/openms-in-knime.html "For a more specific example of how to use KNIME, view our tutorial." should link to the tutorial
- is there tutorial that uses KNIME integrated somewhere? did not find it

**Comment by ghost** [comment]
> * https://greengypsy-staging-openms.readthedocs.io/en/final-touches/docs/introduction/background.html needs a bit of rework I think. See e.g., the section in https://pyopenms.readthedocs.io/en/latest/introduction.html#background . This seems a bit more complete.

I've had a look at this information and find it difficult to read, though it is more in-depth. I've tried to simplify it but have obviously missed some information. Would you be able to mention what concepts need to be included to make this section more complete?

**Review by timosachsenberg — APPROVED** [review]

**Pull request merged**
