### PR TITLE
Large restructure of docs

### PR DESCRIPTION
**Pull request by jpfeuffer**
- Use absolute paths for assets unless they really are in a subfolder of the current document
- Move install instructions into applications and tools to have installation instructions for every entry point
- Use includes to remove redundancy in install instructions
- Use the version macro more
- Add mamba as alternative to conda and rewrite
- Add new singularity images as possible install
- Restructure workflow section:
  - Overview -> Recommended workflow systems
  - Each workflow system (if applicable) gets:
    - Install
    - Workflows
    - Tutorial

### CODE REVIEW

**Comment by matteopilz** [comment]
I think it has been there before, but we get an error with the CDash link and a twitter timeout in the build-sphinx action. Should we ignore this or is there a way to fix it?

**Comment by jpfeuffer** [comment]
We could exclude them from link checking but it's indeed not too urgent.

**Review by matteopilz — APPROVED** [review]

**Comment by timosachsenberg** [comment]
hmm sphinx failed ?

**Comment by jpfeuffer** [comment]
No, why?

**Comment by timosachsenberg** [comment]
CI/Sphinx return value

**Comment by timosachsenberg** [comment]
https://github.com/OpenMS/OpenMS-docs/actions/runs/4809486231/jobs/8560798844?pr=198

**Pull request merged**
