### PR TITLE
Add user tutorial: handouts for training

### LINKED ISSUE #2: Handouts for training

### PR DESCRIPTION
**Pull request by tapaswenipathak**
Fixes https://github.com/OpenMS/OpenMS-docs/issues/2.

## Describe the change

Ref: https://github.com/OpenMS/OpenMS-docs/issues/4#issuecomment-1125150286.

## PR checklist

- [x] I have added description of the change I'm proposing in the OpenMS Documentation.
- [x] I have read and followed [OpenMS Documentation Contributing guidelines](CONTRIBUTING.md).
- [x] I have attached a screenshot of the relevant area after this change.
- [x] `CHANGELOG.md` is updated.
- [x] I have added my name in [CONTRIBUTING.md](CONTRIBUTING.md#openms-documentation-contributors).

### CODE REVIEW

**Comment by timosachsenberg** [comment]
Should we merge this? Todo: the later chapters

**Comment by tapaswenipathak** [comment]
On Wed, Jun 8, 2022 at 5:08 PM Timo Sachsenberg
***@***.***> wrote:
>
> Should we merge this? Todo: the later chapters

1. i want to observe the ripple when there is no user-tutorial of
handout training material type. should it be in training materials
under downloads?
2. if everything goes well, saturday aoe i build
openms.readthedocs.io/en/develop, request reviews in #general and work
on completing it.
3. more time to think, to have information from this tut available for
quick reads, idk, how.
4. let everyone brainstorm on ideas when they don't see this user-tutorial.
5. it is not ready yet and i don't have the capacity to complete it
before sunday.

**Comment by timosachsenberg** [comment]
thanks for the update! no worries just wanted to check if I can do something.
 I think we can just link to the existing pdf until this PR is done if we want. Could even be directly linked from the page this goes in later.
no rush... just take all the time you need!

**Comment by jpfeuffer** [comment]
This is by far not finished. Until this is not finished I don't think archiving OpenMS/Tutorials is a blocker.
(I am even hesitant to archive it before we have a working version here, since otherwise we cannot change anything for workshops anymore).

**Comment by jpfeuffer** [comment]
In general, this is on the right track. You can merge this and finish later, or add to this PR. I don't care much.

**Pull request closed without merging**
